### PR TITLE
Jb setup

### PR DESCRIPTION
**Pull request by JakeBrose**
## DESCRIPTION
Added pug templates for my account, view orders, edit account info, and view payment types. Also added a ctrl for account view. View displays user info of logged in user.
Why did you do it?

## STEPS TO TEST
1. run npm test
2. in the browser, load local host 8080
3. Click Register
4. Click logout 
5. Click log in 
6. Click my account

## REFERENCE
#9

### CODE REVIEW

**Comment by ben-marcantel** [comment]
looks good!

**Comment by kylesaldana5** [comment]
Works on my end 🥈

**Comment by EduardoDuQuesne** [comment]
Workin! 😀

**Comment by Craig-Orcutt** [comment]
works grewat

**Pull request merged**
